/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;

import Data.Connect;
import Data.SinhVienData;
import Data.PhieuMuonData;
import Data.SachData;
import Object.SinhVien;
import Object.NhaXb;
import Object.PhieuMuon;
import Object.Sach;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import Data.Rangbuoc;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/**
 *
 * @author Gaara
 */
public class JAdminUpdate extends javax.swing.JFrame {

    SachData sachdata = new SachData();
    SinhVienData sinhviendata = new SinhVienData();
    PhieuMuonData phieumuondata = new PhieuMuonData();
    public static Statement st = null;
    public static ResultSet rs = null;
    public static PreparedStatement ps = null;
    public static PreparedStatement ps2 = null;
    public static String sqlSach = "SELECT * FROM SACH order by Ma_Sach asc";
    public static String sqlSinhVien = "SELECT * FROM Sinh_Vien order by id asc";
    public static String sqlPhieu = "SELECT * FROM PHIEU_MUON order by Ma_Phieu_muon asc";

    /**
     * Creates new form JAdminUpdate
     */
    public JAdminUpdate() {
        this.setLocation(100, 10);
        initComponents();
        UpdateTable.LoadData(sqlSach, tbSach);
        UpdateTable.LoadData(sqlSinhVien, tbSinhVien);
        UpdateTable.LoadData(sqlPhieu, tbMuon);
        ProcessCrt(false);
        ProcessCrt2(false);
        ProcessCrt3(false);
        setLocationRelativeTo(null);
    }

    public void ProcessCrt(boolean b) {
        this.btAddSach.setEnabled(b);
        this.btEditSach.setEnabled(b);
        this.btDelSach.setEnabled(b);
    }

    public void ProcessCrt2(boolean b) {
        this.btAddSinhVien.setEnabled(b);
        this.btEditSinhVien.setEnabled(b);
        this.btDelSinhVien.setEnabled(b);
    }

    public void ProcessCrt3(boolean b) {
        this.btAddPhieu.setEnabled(b);
        this.btEditPhieu.setEnabled(b);
        this.btDelPhieu.setEnabled(b);
        this.btTra.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtTenSach = new javax.swing.JTextField();
        txtTenTacGia = new javax.swing.JTextField();
        txtNhaXb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLookSach = new javax.swing.JTextField();
        btLookSach = new javax.swing.JButton();
        txtMaSach = new javax.swing.JTextField();
        btAddSach = new javax.swing.JButton();
        btEditSach = new javax.swing.JButton();
        btDelSach = new javax.swing.JButton();
        btNewSach = new javax.swing.JButton();
        btRet = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtNguoiMuon = new javax.swing.JTextField();
        txtSachMuon = new javax.swing.JTextField();
        txtNgayMuon = new javax.swing.JTextField();
        txtHanTra = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbMuon = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtLookPhieu = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btLookMuon = new javax.swing.JButton();
        txtMaPhieuMuon = new javax.swing.JTextField();
        btAddPhieu = new javax.swing.JButton();
        btEditPhieu = new javax.swing.JButton();
        btDelPhieu = new javax.swing.JButton();
        btNewPhieu = new javax.swing.JButton();
        btTra = new javax.swing.JButton();
        btRet1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JTextField();
        txtTenSinhVien = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSinhVien = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLookSinhVien = new javax.swing.JTextField();
        btLookSinhVien = new javax.swing.JButton();
        txtMaSinhVien = new javax.swing.JTextField();
        btAddSinhVien = new javax.swing.JButton();
        btEditSinhVien = new javax.swing.JButton();
        btDelSinhVien = new javax.swing.JButton();
        btNewSinhVien = new javax.swing.JButton();
        btRet2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtLop = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        txtTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSachActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mã sách");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tên sách");

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSach);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tên tác giả");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nhà xuất bản");

        btLookSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLookSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/timkiem.png"))); // NOI18N
        btLookSach.setText("Tìm kiếm");
        btLookSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLookSachActionPerformed(evt);
            }
        });

        btAddSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAddSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/them.png"))); // NOI18N
        btAddSach.setText("Thêm");
        btAddSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddSachActionPerformed(evt);
            }
        });

        btEditSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEditSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sua.png"))); // NOI18N
        btEditSach.setText("Sửa");
        btEditSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditSachActionPerformed(evt);
            }
        });

        btDelSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btDelSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa_1.png"))); // NOI18N
        btDelSach.setText("Xóa");
        btDelSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelSachActionPerformed(evt);
            }
        });

        btNewSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNewSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nhapmoi.png"))); // NOI18N
        btNewSach.setText("Nhập mới");
        btNewSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewSachActionPerformed(evt);
            }
        });

        btRet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btRet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quaylai.png"))); // NOI18N
        btRet.setText("Quay lại");
        btRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNewSach, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5)
                                                .addGap(28, 28, 28))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(btAddSach, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(100, 100, 100)
                                                .addComponent(btEditSach, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(btDelSach, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtNhaXb, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btLookSach, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtLookSach, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addGap(288, 288, 288))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(btRet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLookSach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLookSach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNewSach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddSach)
                    .addComponent(btEditSach)
                    .addComponent(btDelSach))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNhaXb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cập Nhật Sách", jPanel2);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Mã phiếu mượn");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Mã Sinh Viên");

        tbMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMuonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbMuon);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Mã Sách");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Ngày mượn");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Hạn trả");

        btLookMuon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLookMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/timkiem.png"))); // NOI18N
        btLookMuon.setText("Tìm kiếm");
        btLookMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLookMuonActionPerformed(evt);
            }
        });

        btAddPhieu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAddPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/them.png"))); // NOI18N
        btAddPhieu.setText("Thêm");
        btAddPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPhieuActionPerformed(evt);
            }
        });

        btEditPhieu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sua.png"))); // NOI18N
        btEditPhieu.setText("Sửa");
        btEditPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditPhieuActionPerformed(evt);
            }
        });

        btDelPhieu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDelPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa_1.png"))); // NOI18N
        btDelPhieu.setText("Xóa");
        btDelPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelPhieuActionPerformed(evt);
            }
        });

        btNewPhieu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNewPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nhapmoi.png"))); // NOI18N
        btNewPhieu.setText("Nhập mới");
        btNewPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewPhieuActionPerformed(evt);
            }
        });

        btTra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trasach.png"))); // NOI18N
        btTra.setText("Trả sách");
        btTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraActionPerformed(evt);
            }
        });

        btRet1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btRet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quaylai.png"))); // NOI18N
        btRet1.setText("Quay lại");
        btRet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRet1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(btLookMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLookPhieu))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(btAddPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(btEditPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                        .addComponent(btDelPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                            .addComponent(txtNguoiMuon)
                                            .addComponent(txtSachMuon))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(txtHanTra)
                                    .addComponent(btNewPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btTra))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(btRet1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLookPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLookMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNewPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddPhieu)
                    .addComponent(btEditPhieu)
                    .addComponent(btDelPhieu)
                    .addComponent(btTra, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23)
                    .addComponent(txtNguoiMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txtSachMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRet1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Cập Nhật Phiếu Mượn", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Mã Sinh Viên");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Mật Khẩu");

        tbSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbSinhVien.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tbSinhVienComponentAdded(evt);
            }
        });
        tbSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSinhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbSinhVien);
        tbSinhVien.getAccessibleContext().setAccessibleDescription("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Tên Sinh Viên");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Tuổi");

        txtLookSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLookSinhVienActionPerformed(evt);
            }
        });

        btLookSinhVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLookSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/timkiem.png"))); // NOI18N
        btLookSinhVien.setText("Tìm kiếm");
        btLookSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLookSinhVienActionPerformed(evt);
            }
        });

        txtMaSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSinhVienActionPerformed(evt);
            }
        });

        btAddSinhVien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAddSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/them.png"))); // NOI18N
        btAddSinhVien.setText("Thêm");
        btAddSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddSinhVienActionPerformed(evt);
            }
        });

        btEditSinhVien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sua.png"))); // NOI18N
        btEditSinhVien.setText("Sửa");
        btEditSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditSinhVienActionPerformed(evt);
            }
        });

        btDelSinhVien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDelSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa_1.png"))); // NOI18N
        btDelSinhVien.setText("Xóa");
        btDelSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelSinhVienActionPerformed(evt);
            }
        });

        btNewSinhVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNewSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nhapmoi.png"))); // NOI18N
        btNewSinhVien.setText("Nhập mới");
        btNewSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewSinhVienActionPerformed(evt);
            }
        });

        btRet2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btRet2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quaylai.png"))); // NOI18N
        btRet2.setText("Quay lại");
        btRet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRet2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Lớp");

        txtLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(btLookSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLookSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaSinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                                    .addComponent(txtTenSinhVien))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btNewSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(btDelSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(94, 94, 94)))
                            .addComponent(txtLop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(btRet2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLookSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtLookSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNewSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDelSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btRet2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Cập Nhật Sinh Viên", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSachMouseClicked
        // TODO add your handling code here:
        ProcessCrt(true);
        this.btAddSach.setEnabled(false);
        try {
            int row = this.tbSach.getSelectedRow();
            String IDrow = (this.tbSach.getModel().getValueAt(row, 0)).toString();
            String sql1 = "SELECT * FROM SACH where Ma_Sach='" + IDrow + "'";
            ResultSet rs = UpdateTable.ShowTextField(sql1);
            if (rs.next()) {
                this.txtMaSach.setText(rs.getString("Ma_Sach"));
                this.txtTenSach.setText(rs.getString("Ten_Sach"));
                this.txtNhaXb.setText(rs.getString("Nha_Xb"));
                this.txtTenTacGia.setText(rs.getString("Ten_Tac_gia"));
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tbSachMouseClicked

    private void btLookSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLookSachActionPerformed
        // TODO add your handling code here:
        if (this.txtLookSach.getText().length() == 0) {
            String sql1 = "SELECT * from SACH ";
            UpdateTable.LoadData(sql1, tbSach);
        } else {
            String sql1 = "SELECT * from SACH WHERE Ma_Sach like N'%" + this.txtLookSach.getText() + "%' "
                    + "or Ten_Sach like N'%" + this.txtLookSach.getText() + "%'"
                    + "or Ten_Tac_gia like N'%" + this.txtLookSach.getText() + "%'"
                    + "or Nha_Xb like N'%" + this.txtLookSach.getText() + "%'";
            UpdateTable.LoadData(sql1, tbSach);
        }

    }//GEN-LAST:event_btLookSachActionPerformed

    private void btAddSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddSachActionPerformed
        // TODO add your handling code here:
        if (txtMaSach.getText().equals("") || txtTenSach.getText().equals("") || txtTenTacGia.getText().equals("") || txtNhaXb.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Đề Nghị Nhập Đầy Đủ Thông Tin", "Thông báo", 2);
        } else {
            try{
                if (this.txtMaSach.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Mã sách không thể bỏ trống", "thông báo", 2);
                } else if (this.txtMaSach.getText().length() > 10) {
                    JOptionPane.showMessageDialog(null, "Mã sách không được lớn hơn 10 ký tự", "thông báo", 2);
                } else{ 
                    Sach b = new Sach(this.txtMaSach.getText(),this.txtTenSach.getText(), this.txtTenTacGia.getText(), this.txtNhaXb.getText());
                    SachData.InsertSach(b);
                    this.btLookSach.doClick();
                }
            }  
            catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btAddSachActionPerformed

    private void btNewSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewSachActionPerformed
        // TODO add your handling code here:
        ProcessCrt(false);
        this.btAddSach.setEnabled(true);
        this.txtMaSach.setText(null);
        this.txtNhaXb.setText(null);
        this.txtTenSach.setText(null);
        this.txtTenTacGia.setText(null);
    }//GEN-LAST:event_btNewSachActionPerformed

    private void btEditSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditSachActionPerformed
        // TODO add your handling code here:
        if (txtMaSach.getText().equals("") || txtTenSach.getText().equals("") || txtTenTacGia.getText().equals("") || txtNhaXb.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Đề Nghị Nhập Đầy Đủ Thông Tin", "Thông báo", 2);
        } else{
                if (this.txtMaSach.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Mã sách không thể bỏ trống", "thông báo", 2);
                } else if (this.txtMaSach.getText().length() > 10) {
                    JOptionPane.showMessageDialog(null, "Mã sách không được lớn hơn 10 ký tự", "thông báo", 2);
                } else {
                    Sach s = new Sach(this.txtMaSach.getText(), this.txtTenSach.getText(), this.txtTenTacGia.getText(), this.txtNhaXb.getText());
                    if (sachdata.UpdateSach(s)) {
                        JOptionPane.showMessageDialog(null, "Bạn đã sửa thành công", "Thông báo", 1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
                    }
                    this.btLookSach.doClick();
                }
            } 
    }//GEN-LAST:event_btEditSachActionPerformed

    private void btDelSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelSachActionPerformed
        // TODO add your handling code here:
        if (this.txtMaSach.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Mã sách không thể bỏ trống", "thông báo", 2);
        } else if (this.txtMaSach.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "Mã sách không được lớn hơn 10 ký tự", "thông báo", 2);
        } else {
            if (sachdata.DeleteSach(this.txtMaSach.getText())) {
                JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công", "Thông báo", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
            }
            this.btLookSach.doClick();
        }
    }//GEN-LAST:event_btDelSachActionPerformed

    private void tbSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSinhVienMouseClicked
        // TODO add your handling code here:
        ProcessCrt2(true);
        this.btAddSinhVien.setEnabled(false);
        try {
            int row = this.tbSinhVien.getSelectedRow();
            String IDrow = (this.tbSinhVien.getModel().getValueAt(row, 0)).toString();
            String sql1 = "SELECT * FROM Sinh_Vien where id='" + IDrow + "'";
            ResultSet rs = UpdateTable.ShowTextField(sql1);
            if (rs.next()) {
                this.txtMaSinhVien.setText(rs.getString("id"));
                this.txtPassword.setText(rs.getString("Password"));
                this.txtTenSinhVien.setText(rs.getString("Ten_Sinh_Vien"));
                this.txtTuoi.setText(rs.getString("Tuoi"));
                this.txtLop.setText(rs.getString("Lop"));
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tbSinhVienMouseClicked

    private void btLookSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLookSinhVienActionPerformed
        // TODO add your handling code here:
        if (this.txtLookSinhVien.getText().length() == 0) {
            String sql1 = "SELECT * from Sinh_Vien ";
            UpdateTable.LoadData(sql1, tbSinhVien);
        } else {
            String sql1 = "SELECT * from Sinh_Vien WHERE id like N'%" + this.txtLookSinhVien.getText() + "%' "
                    + "or Ten_Sinh_Vien like N'%" + this.txtLookSinhVien.getText() + "%'";
            UpdateTable.LoadData(sql1, tbSinhVien);
        }
    }//GEN-LAST:event_btLookSinhVienActionPerformed

    private void btAddSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddSinhVienActionPerformed
        // TODO add your handling code here:
        if (txtMaSinhVien.getText().equals("") || txtPassword.getText().equals("") || txtTenSinhVien.getText().equals("") || txtTuoi.getText().equals("")|| txtLop.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Đề Nghị Nhập Đầy Đủ Thông Tin", "Thông báo", 2);
        } else {
            try {
                if (Rangbuoc.kiemtrasonguyen(txtTuoi.getText()) == true) {
                    if (this.txtMaSinhVien.getText().length() == 0) {
                        JOptionPane.showMessageDialog(null, "Mã sinh viên không thể bỏ trống", "Thông báo", 2);
                    } else if (this.txtMaSinhVien.getText().length() > 10) {
                        JOptionPane.showMessageDialog(null, "Mã sinh viên không được lớn hơn 10 ký tự", "Thông báo", 2);
                    } else {
                        SinhVien s = new SinhVien(this.txtMaSinhVien.getText(), this.txtPassword.getText(), this.txtTenSinhVien.getText(), this.txtTuoi.getText(), this.txtLop.getText());
                        SinhVienData.InsertSinhVien(s);
                        this.btLookSinhVien.doClick();
                    }
                } 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Yêu cầu nhập tuổi ở ô Tuổi", "Thông báo", 2);
            }
        }
    }//GEN-LAST:event_btAddSinhVienActionPerformed

    private void btEditSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditSinhVienActionPerformed
        // TODO add your handling code here:
        if (txtMaSinhVien.getText().equals("") || txtPassword.getText().equals("") || txtTenSinhVien.getText().equals("") || txtTuoi.getText().equals("") || txtLop.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Đề Nghị Nhập Đầy Đủ Thông Tin", "Thông báo", 2);
        } else {
            try {
                if (this.txtMaSinhVien.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Mã khách hàng không thể bỏ trống", "Thông báo", 2);
                } else if (this.txtMaSinhVien.getText().length() > 10) {
                    JOptionPane.showMessageDialog(null, "Mã khách hàng không được lớn hơn 10 ký tự", "Thông báo", 2);
                } else {
                    SinhVien s = new SinhVien(this.txtMaSinhVien.getText(), this.txtPassword.getText(), this.txtTenSinhVien.getText(),this.txtTuoi.getText(),this.txtLop.getText());
                    if (sinhviendata.UpdateSinhVien(s)) {
                        JOptionPane.showMessageDialog(null, "Bạn đã sửa thành công", "Thông báo", 1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
                    }
                    this.btLookSinhVien.doClick();
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btEditSinhVienActionPerformed

    private void btDelSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelSinhVienActionPerformed
        // TODO add your handling code here:
        if (this.txtMaSinhVien.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Mã sách không thể bỏ trống", "Thông báo", 2);
        } else if (this.txtMaSinhVien.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "Mã sách không được lớn hơn 10 ký tự", "Thông báo", 2);
        } else {
            if (sinhviendata.DeleteSinhVien(this.txtMaSinhVien.getText())) {
                JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công", "Thông báo", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
            }
            this.btLookSinhVien.doClick();
        }
    }//GEN-LAST:event_btDelSinhVienActionPerformed

    private void btNewSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewSinhVienActionPerformed
        // TODO add your handling code here:
        ProcessCrt2(false);
        this.btAddSinhVien.setEnabled(true);
        this.txtMaSinhVien.setText(null);
        this.txtPassword.setText(null);
        this.txtTenSinhVien.setText(null);
        this.txtTuoi.setText(null);
        this.txtLop.setText(null);
    }//GEN-LAST:event_btNewSinhVienActionPerformed

    private void tbMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMuonMouseClicked
        // TODO add your handling code here:
        ProcessCrt3(true);
        this.btAddPhieu.setEnabled(false);
        try {
            int row = this.tbMuon.getSelectedRow();
            String IDrow = (this.tbMuon.getModel().getValueAt(row, 0)).toString();
            String sql1 = "SELECT * FROM PHIEU_MUON where Ma_Phieu_muon='" + IDrow + "'";
            ResultSet rs = UpdateTable.ShowTextField(sql1);
            if (rs.next()) {
                this.txtMaPhieuMuon.setText(rs.getString("Ma_Phieu_muon"));
                this.txtNguoiMuon.setText(rs.getString("Ma_Sinh_Vien"));
                this.txtSachMuon.setText(rs.getString("Ma_Sach"));
                this.txtNgayMuon.setText(rs.getString("Ngay_muon"));
                this.txtHanTra.setText(rs.getString("Han_tra"));
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tbMuonMouseClicked

    private void btLookMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLookMuonActionPerformed
        // TODO add your handling code here:
        if (this.txtLookPhieu.getText().length() == 0) {
            String sql1 = "SELECT * from PHIEU_MUON ";
            UpdateTable.LoadData(sql1, tbMuon);
        } else {
            String sql1 = "SELECT * from PHIEU_MUON WHERE Ma_Phieu_muon like N'%" + this.txtLookPhieu.getText() + "%' "
                    + "or id like N'%" + this.txtLookPhieu.getText() + "%' or Ma_Sach like N'%" + this.txtLookPhieu.getText() + "%'";
            UpdateTable.LoadData(sql1, tbSach);
        }
    }//GEN-LAST:event_btLookMuonActionPerformed

    private void btAddPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPhieuActionPerformed
            if (txtMaPhieuMuon.getText().equals("") || txtNguoiMuon.getText().equals("") || txtSachMuon.getText().equals("") || txtNgayMuon.getText().equals("") || txtHanTra.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Đề Nghị Nhập Đầy Đủ Thông Tin", "Thông báo", 2);
            } else {
                try {
                    if (this.txtMaPhieuMuon.getText().length() == 0) {
                        JOptionPane.showMessageDialog(null, "Mã phiếu mượn không thể bỏ trống", "thông báo", 2);
                    } else if (this.txtMaPhieuMuon.getText().length() > 10) {
                                JOptionPane.showMessageDialog(null, "Mã phiếu mượn không được lớn hơn 10 ký tự", "thông báo", 2);
                    } else {
                            PhieuMuon p = new PhieuMuon(this.txtMaPhieuMuon.getText(), this.txtNguoiMuon.getText(), this.txtSachMuon.getText(),
                                    Date.valueOf(this.txtNgayMuon.getText()), Date.valueOf(this.txtHanTra.getText()));
                            PhieuMuonData.InsertPhieu(p);
                            this.btLookMuon.doClick();
                        }
                    
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Yêu Cầu Nhập Vào Ngày Tháng Năm Ở Ô Ngày Mượn , Hạn Trả", "Thông báo", 2);
                    }
            }
    }//GEN-LAST:event_btAddPhieuActionPerformed

    private void btEditPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditPhieuActionPerformed
        // TODO add your handling code here:
        if (txtMaPhieuMuon.getText().equals("") || txtNguoiMuon.getText().equals("") || txtSachMuon.getText().equals("") || txtNgayMuon.getText().equals("") || txtHanTra.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Đề Nghị Nhập Đầy Đủ Thông Tin", "Thông báo", 2);
        } else {
            try {
                if (this.txtMaPhieuMuon.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Mã phiếu mượn không thể bỏ trống", "thông báo", 2);
                } else if (this.txtMaPhieuMuon.getText().length() > 10) {
                    JOptionPane.showMessageDialog(null, "Mã phiếu mượn không được lớn hơn 10 ký tự", "thông báo", 2);
                } else {
                    PhieuMuon p = new PhieuMuon(this.txtMaPhieuMuon.getText(), this.txtNguoiMuon.getText(),
                            this.txtSachMuon.getText(), Date.valueOf(this.txtNgayMuon.getText()), Date.valueOf(this.txtHanTra.getText()));
                    if (phieumuondata.UpdatePhieu(p)) {
                        JOptionPane.showMessageDialog(null, "Bạn đã sửa thành công", "Thông báo", 1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
                    }
                    this.btLookMuon.doClick();
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Yêu Cầu Nhập Vào Ngày Tháng Năm Ở Ô Ngày Mượn , Hạn Trả", "Thông báo", 2);
            }
        }
    }//GEN-LAST:event_btEditPhieuActionPerformed

    private void btDelPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelPhieuActionPerformed
        // TODO add your handling code here:
        if (this.txtMaPhieuMuon.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Mã phiếu không thể bỏ trống", "thông báo", 2);
        } else if (this.txtMaPhieuMuon.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "Mã phiếu không được lớn hơn 10 ký tự", "thông báo", 2);
        } else {
            if (phieumuondata.DeletePhieu(this.txtMaPhieuMuon.getText())) {
                JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công", "Thông báo", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
            }
            this.btLookMuon.doClick();
        }

    }//GEN-LAST:event_btDelPhieuActionPerformed

    private void btNewPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewPhieuActionPerformed
        // TODO add your handling code here:
        this.txtMaPhieuMuon.setText(null);
        this.txtNguoiMuon.setText(null);
        this.txtSachMuon.setText(null);
        this.txtNgayMuon.setText(null);
        this.txtHanTra.setText(null);
        ProcessCrt3(false);
        this.btAddPhieu.setEnabled(true);
    }//GEN-LAST:event_btNewPhieuActionPerformed

    private void btRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetActionPerformed
        // TODO add your handling code here:
        Chucnang t = new Chucnang();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_btRetActionPerformed

    private void btTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraActionPerformed
        String sql2 = "UPDATE PHIEU_MUON SET NgayTra = (select GETDATE()) where Ma_Phieu_muon = ?";
        String hantra = null;
        try 
        {
            ps2 = Connect.getConnect().prepareStatement(sql2);
            ps2.setString(1, this.txtMaPhieuMuon.getText());
            ps2.executeUpdate();
            this.btLookMuon.doClick();
            st = Connect.getConnect().createStatement();
            String select = "select * from PHIEU_MUON where Ma_Phieu_Muon ='"+this.txtMaPhieuMuon.getText()+"'";
            rs = st.executeQuery(select);
            while(rs.next())
            {
                hantra = rs.getString(6);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JAdminUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
           java.util.Date date1 = null;
           java.util.Date date2 = null;
           long songay = 0;
           long songaynew = 0;
           
        try 
            
        {
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(hantra);
            date2 = new SimpleDateFormat("yyyy-MM-dd").parse(txtHanTra.getText());
            songay = -(date1.getTime() - date2.getTime());
          
        } catch (ParseException ex) {
            Logger.getLogger(JAdminUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
        float songaytinh = (float)songay /(1000*864000);
        if(songaytinh < 0)
        {
            JOptionPane.showMessageDialog(null, "Quá hạn phạt 10.000vnd", "Thông báo", 1);
        try {
            //xoa sach
            String delete ="delete PHIEU_MUON where Ma_Phieu_muon ='"+this.txtMaPhieuMuon.getText()+"'";
            ps2 = Connect.getConnect().prepareStatement(delete);
            ps2.executeUpdate();
            ps.setString(2, this.txtSachMuon.getText());
            ps.execute();
            this.btLookMuon.doClick();
            JOptionPane.showMessageDialog(null, "Trả sách thành công", "Thông báo", 1);
        } catch (Exception ex) {
        }
        }
        else
        {
            try {
            
                //xoa sach
            String delete ="delete PHIEU_MUON where Ma_Phieu_muon ='"+this.txtMaPhieuMuon.getText()+"'";
            ps2 = Connect.getConnect().prepareStatement(delete);
            ps2.executeUpdate();
            ps.setString(2, this.txtSachMuon.getText());
            ps.execute();
            this.btLookMuon.doClick();
            
            
            JOptionPane.showMessageDialog(null, "Trả sách thành công", "Thông báo", 1);
        } catch (Exception ex) {
        }
        }
    }//GEN-LAST:event_btTraActionPerformed

    private void txtLookSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLookSinhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLookSinhVienActionPerformed

    private void txtMaSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSinhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSinhVienActionPerformed

    private void txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSachActionPerformed

    private void btRet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRet1ActionPerformed
        // TODO add your handling code here:
         Chucnang t = new Chucnang();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_btRet1ActionPerformed

    private void btRet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRet2ActionPerformed
        // TODO add your handling code here:
         Chucnang t = new Chucnang();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_btRet2ActionPerformed

    private void txtLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLopActionPerformed

    private void tbSinhVienComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tbSinhVienComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSinhVienComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdminUpdate().setVisible(true);
            }
        });
    }

    public JTable getTbSach() {
        return tbSach;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddPhieu;
    private javax.swing.JButton btAddSach;
    private javax.swing.JButton btAddSinhVien;
    private javax.swing.JButton btDelPhieu;
    private javax.swing.JButton btDelSach;
    private javax.swing.JButton btDelSinhVien;
    private javax.swing.JButton btEditPhieu;
    private javax.swing.JButton btEditSach;
    private javax.swing.JButton btEditSinhVien;
    private javax.swing.JButton btLookMuon;
    private javax.swing.JButton btLookSach;
    private javax.swing.JButton btLookSinhVien;
    private javax.swing.JButton btNewPhieu;
    private javax.swing.JButton btNewSach;
    private javax.swing.JButton btNewSinhVien;
    private javax.swing.JButton btRet;
    private javax.swing.JButton btRet1;
    private javax.swing.JButton btRet2;
    private javax.swing.JButton btTra;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbMuon;
    private javax.swing.JTable tbSach;
    private javax.swing.JTable tbSinhVien;
    private javax.swing.JTextField txtHanTra;
    private javax.swing.JTextField txtLookPhieu;
    private javax.swing.JTextField txtLookSach;
    private javax.swing.JTextField txtLookSinhVien;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMaPhieuMuon;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNguoiMuon;
    private javax.swing.JTextField txtNhaXb;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSachMuon;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTenSinhVien;
    private javax.swing.JTextField txtTenTacGia;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
